# Generated by Django 4.0.4 on 2022-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff')], default='Staff', max_length=50, null=True),
        ),
    ]
